version: '2'
services:
  web:
    build: .
    volumes:
      - .:/var/www/project
  nginx:
    image: nginx:1.13.6
    links:
      - web
    volumes_from:
      - web
    volumes:
          - ./docker/nginx_vhost.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    ports:
      - "80:80"